# .scrutinizer.yml
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'

    nodes:
        php71:
            environment:
                php: 7.1 # Common versions: 5.4, 5.5, 5.6, 7.1 or hhvm

        php56:
            environment:
                php: 5.6 # Common versions: 5.4, 5.5, 5.6, 7.1 or hhvm

        hhvm:
            environment:
                php: hhvm # Common versions: 5.4, 5.5, 5.6, 7.1 or hhvm


checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*


